### ISSUE TITLE
Review Request

### ISSUE THREAD

**Issue by whyrusleeping** [david415/ipfs-onion-transport#1]
The overall approach looks good, and the code looks ok from an "is this good go-ipfs style code?" perspective, but I can't review this technically as I don't have a solid understanding of the TOR addressing scheme, what the addresses signify and the different security implications that doing things a certain way might have.

If you could provide me a short writeup on what Tor multiaddrs for listeners and dialers might look like, and a description of the process of connecting to a Tor service, that would be very helpful.

**Comment by david415** [comment]
here's the tor control port spec:
https://gitweb.torproject.org/torspec.git/tree/control-spec.txt

recently the ephemeral onion service API was added to the control spec. there's an ADD_ONION and DEL_ONION commands. ADD_ONION can optionally specify the onion service private key, otherwise tor will generate a new key. You can also have the tor control port tell you the contents of the new key or not.

currently tor onion address are 80 bits of truncated hash of the public key... in base32 format.

i left a comment here:
https://github.com/ipfs/go-libp2p/pull/79
